export const HEADER_LANGUAGE_KEYS = {
    HEADER_HOME: 'HEADER_HOME',
    HEADER_PRE_CHECK: 'HEADER_PRE_CHECK',
    HEADER_SEARCH: 'HEADER_SEARCH',
    HEADER_BLIF_DOWNLOADS: 'HEADER_BLIF_DOWNLOADS',
    HEADER_REPORTING: 'HEADER_REPORTING',
    HEADER_EXCHANGES: 'HEADER_EXCHANGES',
};
