export const ARRAY_MAP_KEYS = {
    LABEL: 'LABEL',
    VALUE: 'VALUE',
    INDEX: 'INDEX',
    ID: 'ID',
    ON_CLICK: 'ON_CLICK',
    FILTER_TYPE: 'FILTER_TYPE',
    OPTIONS: 'OPTIONS',
    ON_CHANGE: 'ON_CHANGE',
};

export const FILTER_TYPES = {
    SELECT_INPUT: 'SELECT_INPUT',
    TEXT_INPUT: 'TEXT_INPUT',
};

export const LOCAL_LANGUAGE = 'LANGUAGE';
