export const DOWNLOADS_LANGUAGE_KEYS = {
    DOWNLOADS_HEADING: 'DOWNLOADS_HEADING',
    DOWNLOADS_START_DATE: 'DOWNLOADS_START_DATE',
    DOWNLOADS_END_DATE: 'DOWNLOADS_END_DATE',
    DOWNLOADS_FILE: 'DOWNLOADS_FILE',
    DOWNLOADS_DOWNLOADS: 'DOWNLOADS_DOWNLOADS',
};

export const FILE_SEARCH_FILTER_LANGUAGE_KEYS = {
    LABEL: 'FILE_SEARCH_FILTER_LABEL',
};

export const START_DATE_FILTER_LANGUAGE_KEYS = {
    LABEL: 'START_DATE_FILTER_LABEL',
};

export const END_DATE_FILTER_LANGUAGE_KEYS = {
    LABEL: 'END_DATE_FILTER_LABEL',
};
