export const EXCHANGES_LANGUAGE_KEYS = {
    EXCHANGES_HEADING: 'EXCHANGES_HEADING',
    EXCHANGES_ABBREV: 'EXCHANGES_ABBREV',
    EXCHANGES_NAME: 'EXCHANGES_NAME',
    EXCHANGES_ABBREVIATION2: 'EXCHANGES_ABBREVIATION2',
    EXCHANGES_BOOK: 'EXCHANGES_BOOK',
    EXCHANGES_SECTION: 'EXCHANGES_SECTION',
    EXCHANGES_NPA: 'EXCHANGES_NPA',
    EXCHANGES_EXCHANGES: 'EXCHANGES_EXCHANGES',
};

export const ABBREV_SEARCH_FILTER_LANGUAGE_KEYS = {
    LABEL: 'ABBREV_SEARCH_FILTER_LABEL',
};

export const NAME_SEARCH_FILTER_LANGUAGE_KEYS = {
    LABEL: 'NAME_SEARCH_FILTER_LABEL',
};

export const ABBREVIATION2_SEARCH_FILTER_LANGUAGE_KEYS = {
    LABEL: 'ABBREVIATION2_SEARCH_FILTER_LABEL',
};

export const BOOK_SEARCH_FILTER_LANGUAGE_KEYS = {
    LABEL: 'BOOK_SEARCH_FILTER_LABEL',
};

export const SECTION_SEARCH_FILTER_LANGUAGE_KEYS = {
    LABEL: 'SECTION_SEARCH_FILTER_LABEL',
};

export const NPA_SEARCH_FILTER_LANGUAGE_KEYS = {
    LABEL: 'NPA_SEARCH_FILTER_LABEL',
};

export const EXCHANGES_TABLE_HEADER_KEYS = {
    EXCHANGES_ABBREV: 'EXCHANGES_ABBREV',
    EXCHANGES_NAME: 'EXCHANGES_NAME',
    EXCHANGES_ABBREVIATION2: 'EXCHANGES_ABBREVIATION2',
    EXCHANGES_BOOK: 'EXCHANGES_BOOK',
    EXCHANGES_SECTION: 'EXCHANGES_SECTION',
    EXCHANGES_NPA: 'EXCHANGES_NPA',
};
