export const PRECHECK_LANGUAGE_KEYS = {
    PRECHECK_HEADING: 'PRECHECK_HEADING',
    PRECHECK_FILE: 'PRECHECK_FILE',
    PRECHECK_PROVINCE: 'PRECHECK_PROVINCE',
    PRECHECK_CLEC: 'PRECHECK_CLEC',
    PRECHECK_BRG_INDICATOR: 'PRECHECK_BRG_INDICATOR',
    PRECHECK_REJECTS: 'PRECHECK_REJECTS',
    PRECHECK_ALL: 'PRECHECK_ALL',
    PRECHECK_QC: 'PRECHECK_QC',
    PRECHECK_FIDO: 'PRECHECK_FIDO',
    PRECHECK_BUSINESS: 'PRECHECK_BUSINESS',
    PRECHECK_RESIDENTIAL: 'PRECHECK_RESIDENTIAL',
    PRECHECK_ONLY_REJECTS: 'PRECHECK_ONLY_REJECTS',
    PRECHECK_NO_REJECTS: 'PRECHECK_NO_REJECTS',
    PRECHECK_PRE_CHECK: 'PRECHECK_PRE_CHECK',
};

export const PROVINCE_FILTER_OPTIONS_KEYS = {
    ALL: 'PROVINCE_FILTER_ALL',
    QC: 'PROVINCE_FILTER_QC',
};
export const REJECTS_FILTER_OPTIONS_KEYS = {
    ALL: 'REJECTS_FILTER_ALL',
    ONLY_REJECTS: 'REJECTS_FILTER_ONLY_REJECTS',
    NO_REJECTS: 'REJECTS_FILTER_NO_REJECTS',
};

export const BRG_FILTER_OPTIONS_KEYS = {
    ALL: 'BRG_FILTER_ALL',
    RESIDENTIAL: 'BRG_FILTER_RESIDENTIAL',
    BUSINESS: 'BRG_FILTER_BUSINESS',
};

export const CLEC_FILTER_OPTIONS_KEYS = {
    ALL: 'CLEC_FILTER_ALL',
    FIDO: 'CLEC_FILTER_FIDO',
};
