export const PRECHECK_LANGUAGE_KEYS = {
    PRECHECK_HEADING: 'PRECHECK_HEADING',
    PRECHECK_FILE: 'PRECHECK_FILE',
    PRECHECK_PROVINCE: 'PRECHECK_PROVINCE',
    PRECHECK_CLEC: 'PRECHECK_CLEC',
    PRECHECK_BRG_INDICATOR: 'PRECHECK_BRG_INDICATOR',
    PRECHECK_REJECTS: 'PRECHECK_REJECTS',
    PRECHECK_ALL: 'PRECHECK_ALL',
    PRECHECK_QC: 'PRECHECK_QC',
    PRECHECK_FIDO: 'PRECHECK_FIDO',
    PRECHECK_BUSINESS: 'PRECHECK_BUSINESS',
    PRECHECK_RESIDENTIAL: 'PRECHECK_RESIDENTIAL',
    PRECHECK_ONLY_REJECTS: 'PRECHECK_ONLY_REJECTS',
    PRECHECK_NO_REJECTS: 'PRECHECK_NO_REJECTS',
    PRECHECK_PRE_CHECK: 'PRECHECK_PRE_CHECK',
};

export const FILE_SEARCH_FILTER_LANGUAGE_KEYS = {
    LABEL: 'FILE_SEARCH_FILTER_LABEL',
};

export const PROVINCE_FILTER_LANGUAGE_KEYS = {
    LABEL: 'PROVINCE_FILTER_LABEL',
    ALL: 'PROVINCE_FILTER_ALL',
    QC: 'PROVINCE_FILTER_QC',
};

export const REJECTS_FILTER_LANGUAGE_KEYS = {
    LABEL: 'REJECTS_FILTER_LABEL',
    ALL: 'REJECTS_FILTER_ALL',
    ONLY_REJECTS: 'REJECTS_FILTER_ONLY_REJECTS',
    NO_REJECTS: 'REJECTS_FILTER_NO_REJECTS',
};

export const BRG_FILTER_LANGUAGE_KEYS = {
    LABEL: 'BRG_FILTER_LABEL',
    ALL: 'BRG_FILTER_ALL',
    RESIDENTIAL: 'BRG_FILTER_RESIDENTIAL',
    BUSINESS: 'BRG_FILTER_BUSINESS',
};

export const CLEC_FILTER_LANGUAGE_KEYS = {
    LABEL: 'CLEC_FILTER_LABEL',
    ALL: 'CLEC_FILTER_ALL',
    FIDO: 'CLEC_FILTER_FIDO',
};

export const PRE_CHECK_TABLE_HEADER_KEYS = {
    PRE_CHECK_EXCHANGE: 'PRE_CHECK_EXCHANGE',
    PRE_CHECK_SL: 'PRE_CHECK_SL',
    PRE_CHECK_SPID: 'PRE_CHECK_SPID',
    PRE_CHECK_ACTION: 'PRE_CHECK_ACTION',
    PRE_CHECK_NL: 'PRE_CHECK_NL',
    PRE_CHECK_NUMBER: 'PRE_CHECK_NUMBER',
    PRE_CHECK_BRG: 'PRE_CHECK_BRG',
    PRE_CHECK_NAME: 'PRE_CHECK_NAME',
    PRE_CHECK_LOCATION: 'PRE_CHECK_LOCATION',
    PRE_CHECK_ADDRESS: 'PRE_CHECK_ADDRESS',
    PRE_CHECK_CFC: 'PRE_CHECK_CFC',
    PRE_CHECK_REJECT_CODE: 'PRE_CHECK_REJECT_CODE',
    PRE_CHECK_POLICY_CODE: 'PRE_CHECK_POLICY_CODE',
};
