export const SEARCH_LANGUAGE_KEYS = {
    SEARCH_HEADING: 'SEARCH_HEADING',
    SEARCH_PHONE_NUMBER: 'SEARCH_PHONE_NUMBER',
    SEARCH_BUS_OPERATING_NAME: 'SEARCH_BUS_OPERATING_NAME',
    SEARCH_ACTION_INDICATOR: 'SEARCH_ACTION_INDICATOR',
    SEARCH_INTERNAL_STATUS: 'SEARCH_INTERNAL_STATUS',
    SEARCH_START_DATE: 'SEARCH_START_DATE',
    SEARCH_END_DATE: 'SEARCH_END_DATE',
    SEARCH_FILE: 'SEARCH_FILE',
    SEARCH_PROVINCE: 'SEARCH_PROVINCE',
    SEARCH_BRG_INDICATOR: 'SEARCH_BRG_INDICATOR',
    SEARCH_REJECTS: 'SEARCH_REJECTS',
    SEARCH_ALL: 'SEARCH_ALL',
    SEARCH_QC: 'SEARCH_QC',
    SEARCH_BUSINESS: 'SEARCH_BUSINESS',
    SEARCH_RESIDENTIAL: 'SEARCH_RESIDENTIAL',
    SEARCH_ONLY_REJECTS: 'SEARCH_ONLY_REJECTS',
    SEARCH_NO_REJECTS: 'SEARCH_NO_REJECTS',
    SEARCH_SEARCH: 'SEARCH_SEARCH',
    SEARCH_A: 'SEARCH_A',
    SEARCH_OI: 'SEARCH_OI',
    SEARCH_D: 'SEARCH_D',
    SEARCH_0000: 'SEARCH_0000',
    SEARCH_0001: 'SEARCH_0001',
    SEARCH_0002: 'SEARCH_0002',
    SEARCH_0010: 'SEARCH_0010',
    SEARCH_0015: 'SEARCH_0015',
    SEARCH_0031: 'SEARCH_0031',
    SEARCH_0032: 'SEARCH_0032',
    SEARCH_0050: 'SEARCH_0050',
};

export const FILE_SEARCH_FILTER_LANGUAGE_KEYS = {
    LABEL: 'FILE_SEARCH_FILTER_LABEL',
};

export const BUS_OPERATING_NAME_FILTER_LANGUAGE_KEYS = {
    LABEL: 'BUS_OPERATING_NAME_FILTER_LABEL',
};

export const PHONE_NUMBER_FILTER_LANGUAGE_KEYS = {
    LABEL: 'PHONE_NUMBER_FILTER_LABEL',
};

export const START_DATE_SEARCH_FILTER_LANGUAGE_KEYS = {
    LABEL: 'START_DATE_SEARCH_FILTER_LABEL',
};

export const END_DATE_SEARCH_FILTER_LANGUAGE_KEYS = {
    LABEL: 'END_DATE_SEARCH_FILTER_LABEL',
};

export const PROVINCE_FILTER_LANGUAGE_KEYS = {
    LABEL: 'PROVINCE_FILTER_LABEL',
    ALL: 'PROVINCE_FILTER_ALL',
    QC: 'PROVINCE_FILTER_QC',
};

export const REJECTS_FILTER_LANGUAGE_KEYS = {
    LABEL: 'REJECTS_FILTER_LABEL',
    ALL: 'REJECTS_FILTER_ALL',
    ONLY_REJECTS: 'REJECTS_FILTER_ONLY_REJECTS',
    NO_REJECTS: 'REJECTS_FILTER_NO_REJECTS',
};

export const BRG_FILTER_LANGUAGE_KEYS = {
    LABEL: 'BRG_FILTER_LABEL',
    ALL: 'BRG_FILTER_ALL',
    RESIDENTIAL: 'BRG_FILTER_RESIDENTIAL',
    BUSINESS: 'BRG_FILTER_BUSINESS',
};

export const ACTION_INDICATOR_FILTER_LANGUAGE_KEYS = {
    LABEL: 'ACTION_INDICATOR_FILTER_LABEL',
    ALL: 'ACTION_INDICATOR_FILTER_ALL',
    A: 'ACTION_INDICATOR_FILTER_A',
    OI: 'ACTION_INDICATOR_FILTER_OI',
    D: 'ACTION_INDICATOR_FILTER_D',
};

export const INTERNAL_STATUS_FILTER_LANGUAGE_KEYS = {
    LABEL: 'INTERNAL_STATUS_FILTER_LABEL',
    ALL: 'INTERNAL_STATUS_FILTER_ALL',
    '0000': 'INTERNAL_STATUS_FILTER_0000',
    '0001': 'INTERNAL_STATUS_FILTER_0001',
    '0002': 'INTERNAL_STATUS_FILTER_0002',
    '0010': 'INTERNAL_STATUS_FILTER_0010',
    '0015': 'INTERNAL_STATUS_FILTER_0015',
    '0031': 'INTERNAL_STATUS_FILTER_0031',
    '0032': 'INTERNAL_STATUS_FILTER_0032',
    '0050': 'INTERNAL_STATUS_FILTER_0050',
};
